# General

backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
glx-copy-from-front = false;

# Corners
corner-radius = 4;
round-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

# Transitions
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# Shadows
shadow = true;
shadow-radius = 12;      # The "spread" of the shadow
shadow-offset-x = -12;   # Horizontal position
shadow-offset-y = -12;   # Vertical position
shadow-opacity = 0.7;    # How dark the shadow is

# Don't draw shadows on hidden windows or specific apps
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Opacity
active-opacity = 1.0;
inactive-opacity = 1.0;

# Dim inactive windows (0.0 to 1.0)
inactive-dim = 0.2;

# Rule: Keep Brave, Terminal and VSCode at 100% even when unfocused
focus-exclude = [
  "class_g = 'Brave-browser'",
  "class_g = 'Code'",
  "class_g = 'Alacritty'"
];


# Background Blur
blur-method = "dual_kawase";
blur-strength = 5;       # 1 to 20 (higher = more blurry)

# Important: Don't blur everything (like the wallpaper itself)
blur-background-exclude = [
  "class_g = 'Brave-browser'",
  "class_g = 'Code'",  
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];
